# Generated by Django 4.2.3 on 2023-07-17 07:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "app_label",
                    models.CharField(max_length=200, verbose_name="app label"),
                ),
                ("order", models.IntegerField(default=1, verbose_name="order")),
                ("visible", models.BooleanField(default=True, verbose_name="visible")),
            ],
            options={
                "verbose_name": "admin app",
                "verbose_name_plural": "admin apps",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="name"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="is default"),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
            },
        ),
        migrations.CreateModel(
            name="AdminModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "object_name",
                    models.CharField(max_length=200, verbose_name="object name"),
                ),
                ("order", models.IntegerField(default=1, verbose_name="order")),
                ("visible", models.BooleanField(default=True, verbose_name="visible")),
                (
                    "admin_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_models",
                        to="app_ordering.adminapp",
                        verbose_name="admin app",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adminapp",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_apps",
                to="app_ordering.profile",
                verbose_name="profile",
            ),
        ),
    ]
