# Generated by Django 4.2.3 on 2023-07-17 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_ordering", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminapp",
            options={
                "ordering": ["order"],
                "verbose_name": "admin app",
                "verbose_name_plural": "admin apps",
            },
        ),
        migrations.AlterModelOptions(
            name="adminmodel",
            options={
                "ordering": ["order"],
                "verbose_name": "admin model",
                "verbose_name_plural": "admin models",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="groups",
            field=models.ManyToManyField(to="auth.group", verbose_name="groups"),
        ),
        migrations.AddField(
            model_name="profile",
            name="users",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="users"
            ),
        ),
        migrations.AlterField(
            model_name="adminapp",
            name="order",
            field=models.IntegerField(db_index=True, default=1, verbose_name="order"),
        ),
    ]
